### ISSUE TITLE
As I user, I want a better legibility on about page so I can read better the text

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#27]
Points that I noticed and that are most critical to the launch:

1. Change the opacity of the text box for legibility to get better. It will help, for example, when there is a photo with more white space, like a sky with clouds;

2. Change the font of the text to a fuller one to improve readability;

**Comment by JoshuSantos** [comment]
[bucolico_200309.pdf](https://github.com/memeLab/bucoli.co/files/4458293/bucolico_200309.pdf)
Ok, I work better by SHOWING than by DESCRIBING, but let's do a little bit of both:

1. What if we ASSUMED a BORDER, since it's a "window of sorts", so that we solve certain legibility problems, like menu and text?

2. What if we make the "SOBRE" text appear from the RIGHT side of the WHITE BORDER so that it merges with the border?

3. What if we put a big "X" in order to close the "SOBRE" text box?

**Comment by bruquevedo** [comment]
@JoshuSantos I talked with Tiago and we suggest you to open a new issue with your points because for this first test we already changed the about text
