### ISSUE TITLE
As a staff member, I want to know how to deliver emails to the inbox, so I reach the users

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#32]
For the first email, we sent, only 28% of the users received the first email. 64% of the emails either went to the spam box or wasn't delivered.

Although we have ways to talk with the testers to add an email address to the "no-spam"

We need to find ways to overcome spam filtering for new users.

They will be put as comments on this card, and when issues are created with them we'll link this issue.

**Comment by vjpixel** [comment]
One user proposed that to just have one link to "bucoli.co" on the email text. I think we should try that.

**Comment by vjpixel** [comment]
I've sent a test email from SendPulse to isNOTspam to check if it can be classified as spam. The result is this report: http://isnotspam.com/newlatestreport.php?email=ins-k6exj0ej%40isnotspam.com

From the report, I suppose that the main problem is test BAYES_99. Search for it on Google, I found: https://stackoverflow.com/questions/33174005/outgoing-email-marked-as-spam-bayes-99

The person that asked the question told that the problem was the HTML of the email, and recommended to check W3 Validator. When I tested the code, it showed more than one thousand errors. @tiagobugarin said he went to the same conclusion.

The link for the validator is here: https://validator.w3.org

**Comment by tiagobugarin** [comment]
As @vjpixel said, I followed the same logic as him and **got to the same results**, therefore I hope that the change to MailChip will do the trick and workaround the our spam problems.

**Comment by bruquevedo** [comment]
As @vjpixel said, we decided to test the use of mailchimp to see if this tool would be more effective in avoiding the spam box.
In the first test sent to our team we had the same problem as before, the email went straight to spam. I marked the email as non-spam, resampled it just for me, and received the email again in the spam box.
From there, I went on to research how to solve the problem.
I found this link https://www.puzzleboxcommunications.com/a-hack-to-keep-your-mailchimp-campaigns-going-spam/ with a step by step and a possible solution to the problem.
I contacted @tiagobugarin  so that he could assist me with the process of changing the DNS and validating the domain as both the link above and this other one, from mailchimp were explaining https://mailchimp.com/pt/help/set-up-custom-domain-authentication-dkim-and-spf/#verify+domain+and+copy+records
@tiagobugarin made the necessary changes and after that, we started sending the test email again. First just for me and him and we received it in the inbox.
We sent it to the rest of the team and everyone also received it in the inbox, as you can check in the issue #37.
So far, we consider the problem to be solved. We will send the emails to the testers and wait their feedback.

**Comment by bruquevedo** [comment]
@tiagobugarin could you please review the issue?

**Comment by tiagobugarin** [comment]
Everything looks right and sounds good.
